### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/class#1]
## Acceptance Criteria
It is clear how JT wants us to proceed

Choose a license for the repositories that protects our IP

**Comment by Parasrah** [comment]
https://github.com/IanLunn/Hover/blob/master/license.txt

**Comment by nscassar** [comment]
Waiting on the meeting with Dr. Moshirpour next week

**Comment by nscassar** [comment]
Didn't realize 'close' meant close the issue, thought it closed just the window

**Comment by nscassar** [comment]
We should put a placeholder at the beginning of each file as a temporary license. A template for one can be found in the following link:
https://softwareengineering.stackexchange.com/questions/68134/best-existing-license-for-closed-source-code

**Comment by ExtraGravity** [comment]
On each file? That's not maintainable, I can almost guarantee that that's not going to happen the way we expect, speaking from previous project experience.

**Comment by Parasrah** [comment]
I agree sounds like a pain to do this on every file, we can just create a `LICENSE` file in the root right?
