### ISSUE TITLE
Decide label styleguide

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/class#21]
- [Robin](https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/)

_Feel free to add other styleguide options here_

**Comment by Parasrah** [comment]
Currently Robin is setup (but the new assignment issues do not adhere to it's conventions)
When we pick one we can set it up here and use a tool to duplicate it to our other repositories

**Comment by jeinglis** [comment]
I'm good with Robin, however due to this being a bit different than their use case (assignment tracking) I have added a label color for submission style (pink)

**Comment by Parasrah** [comment]
Okay I see now what you mean, I was under the impression you guys didn't want to have multiple labels the same color. Your changes make perfect sense
