### ISSUE TITLE
Sprint 101 for the team 

### ISSUE THREAD

**Issue by beaesguerra** [agriculture-capstone/class#24]

**Comment by ExtraGravity** [comment]
Can you explain this to me?

**Comment by beaesguerra** [comment]
I think it would be a good idea for us to get together and explain how we want to do agile development (I think some of us aren't familiar with it)

**Comment by Parasrah** [comment]
We have decided to do this in the the meeting next Thursday

**Comment by beaesguerra** [comment]
Helping Brad out with this. Things to discuss:
- Pipelines in the board
- Pull request process, using git (have unit tests)
- Review and QA process
- Purpose of Sprint Meetings (ie. decide if we will be grooming, review, and/or retrospectives; should we be meeting with stakeholders as well?)
- Storypointing? 
- Purpose of weekly meetings (ie. our scrum) 
- CI
