### ISSUE TITLE
Setup production server environment

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/class#30]
the back-end server needs to be spun up and configured so that it's ready for us

**Comment by Parasrah** [comment]
If we are using my boilerplate I can set up a repo for us

**Comment by ExtraGravity** [comment]
Environment will be run on docker. 
`Docker version 17.09.0-ce, build afdb6d4`
Has been installed on both servers. 

Users have been created
```
enoch-0
bea-0
james-0
moath-0
brad-0
nicholas-0
```
Default passwords created and sent to members. First login forces a password change.

**Comment by ExtraGravity** [comment]
A shared directory at `/shared/` has been made for all users for a staging area.

`cd /shared/` has been added to everyone's `~/.profile` so they start at `/shared/` instead of their home directory after sshing in.
