### ISSUE TITLE
Setup CI Server

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/class#31]
We never did decide on or setup Continuous Integration software.

**Comment by Parasrah** [comment]
I think we were going to use Jenkins?

**Comment by ExtraGravity** [comment]
If it's open source, travis is easier

**Comment by Parasrah** [comment]
In the meeting we decided to use a Jenkins server for CI

**Comment by ExtraGravity** [comment]
Created systems repo that will store this kind of work on it. Made a folder called continuous-integration that will hold the docker image containing our CI configuration.

https://github.com/agriculture-capstone/systems/tree/master/continuous_integration

**Comment by ExtraGravity** [comment]
Create a Github account for CI called boreshabuilder, linked to the boresha.core@gmail.com account. Ask me for details if necessary.

Added public key from `/shared/.ssh/id_rsa.pub` from both servers to boreshabuilder for ssh key github access.

Added an entry in `/etc/ssh/ssh_config` 

```

Host github.com
    HostName github.com
    User git
    IdentityFile /shared/.ssh/id_rsa
```

So connections to Github on the servers will use the key at `/shared/.ssh/id_rsa`

**Comment by ExtraGravity** [comment]
Got everyone to make their own user for jenkins.

Hosted at http://35.190.153.22:8080/login?from=%2F
