### ISSUE TITLE
Choose hosting service (ex: AWS, Bluemix, etc) and set it up

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/class#32]

**Comment by ExtraGravity** [comment]
Google Cloud Service was chosen and trial version activated for boresha.core@gmail.com. Two servers have been created, one for CI (jenkins) and one for public deployment. Both VMs under Google Cloud Service project "Uganda Quality Milk".

OS for both is `Ubuntu Xenial 16.04`
Machine type for both is `g1-small (1 vCPU, 1.7 GB memory)`

jenkins
35.190.153.22

deploy
35.196.181.15
