### ISSUE TITLE
Get host name

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/class#33]
Choose, get and setup a host name for the production environment

**Comment by ExtraGravity** [comment]
Setup production server for to hit domain name.

**Comment by ExtraGravity** [comment]
Done.

http://www.boresha.tech:8080/#/ 

No google cloud server changes needed. Just went to name cheap and used the following advanced DNS settings. Added the A record to point to the IP 35.196.181.15 which is the deploy VM. Removed the redirect and cname record.

![image](https://user-images.githubusercontent.com/9893396/33294830-a1f1be66-d38f-11e7-9f1d-26532923227c.png)
