### ISSUE TITLE
Determine NodeJS framework

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/class#4]
# ExpressJS

## Description

[ExpressJS](https://expressjs.com/) is a tried and true NodeJS framework that has immense popularity and support. It also has very good performance [(see here)](https://raygun.com/blog/node-js-performance-2017/) seemingly only surpassed completely by Raw Node. Express would be a good choice for our application, but it does have its pitfalls. For one, it does not yet support ES6 Promises, a flaw for the development experience (although probably not a serious one). It has lots of middleware available to accomplish various tasks (such as auth), but sometimes this middleware requires some level of assembly before it can be stitched into the express app. 

## Pros
- Well tested through usage
- Lots of community support
- Performant

## Cons
- Callback hell
- Very thin layer of abstraction over raw Node, still have to do a lot of the work ourselves

# FeathersJS

[FeathersJS](https://feathersjs.com/) is a fairly new framework built on top of Express. It seeks to solve a lot of the problems that Express poses for developing backend applications, and has some very unique features that could provide us a lot of benefits. It is believed to be production ready [(see here)](https://docs.feathersjs.com/faq/readme.html#is-feathers-production-ready) and has already seen some major companies adopt it. It integrates well with any framework we choose to use client side, and is noted to pair exceptionally well with React Native. That being said, it does not have the large community support that Express does. 

## Pros
- Superior development experience
 - Promise support
 - Instant real-time REST API's via services
- Datastore agnostic
 - Provides a query interface for us that is consistent across the 15+ database types it supports
 - Could merely swap out databases without thinking twice about it (as long as it is a supported database)
- Provides a lot of the same features as Firebase out of the box
- Built in support for websockets

## Cons
- Smaller community, if we do have problems it might be harder to solve them
- Not as many people using it to discover bugs
- The same performance metrics have not been performed for this framework as it is less popular, although I imagine it to be similar to express
- Does not have a database adapter for Firebase
- Some services are missing Typescript typings
- The Feathers CLI is not compatible with Typescript

_Feel free to add your own to the list with a description of why you think it would fit our use case_

**Comment by Right2Drive** [comment]
# ExpressJS

## Description

[ExpressJS](https://expressjs.com/) is a tried and true NodeJS framework that has immense popularity and support. It also has very good performance [(see here)](https://raygun.com/blog/node-js-performance-2017/) seemingly only surpassed completely by Raw Node. Express would be a good choice for our application, but it does have its pitfalls. For one, it does not yet support ES6 Promises, a flaw for the development experience (although probably not a serious one). It has lots of middleware available to accomplish various tasks (such as auth), but sometimes this middleware requires some level of assembly before it can be stitched into the express app. 

## Pros
- Well tested through usage
- Lots of community support
- Performant

## Cons
- Callback hell
- Very thin layer of abstraction over raw Node, still have to do a lot of the work ourselves

# FeathersJS

[FeathersJS](https://feathersjs.com/) is a fairly new framework built on top of Express. It seeks to solve a lot of the problems that Express poses for developing backend applications, and has some very unique features that could provide us a lot of benefits. It is believed to be production ready [(see here)](https://docs.feathersjs.com/faq/readme.html#is-feathers-production-ready) and has already seen some major companies adopt it. It integrates well with any framework we choose to use client side, and is noted to pair exceptionally well with React Native. That being said, it does not have the large community support that Express does. 

## Pros
- Superior development experience
 - Promise support
 - Instant real-time REST API's via services
- Datastore agnostic
 - Provides a query interface for us that is consistent across the 15+ database types it supports
 - Could merely swap out databases without thinking twice about it
- Provides a lot of the same features as Firebase out of the box

## Cons
- Smaller community, if we do have problems it might be harder to solve them
- Not as many people using it to discover bugs
- The same performance metrics have not been performed for this framework as it is less popular, although I imagine it to be similar to express
- Does not have a database adapter for Firebase

**Comment by Parasrah** [comment]
After looking into FeathersJS at greater length, I am starting to doubt its use case for our project. While it has some awesome features, they are not nearly as battle tested as Express and there are not metrics available to see how they perform in comparison to express. 

I believe that the things that Feathers offers us could be done ourselves with minimal effort, and it would take more time forcing Feathers to work for our use case than it would to just use Express and create some abstractions around the router to make it more friendly.

**Comment by Parasrah** [comment]
I have an express boilerplate that would probably be pretty perfect for what we are doing. It's not exactly conventional (it uses webpack for building), but this gives it some pretty unique advantages (and disadvantages). It's also written using Typescript.

**Comment by Parasrah** [comment]
We have decided to use my node-rest-boilerplate
