### ISSUE TITLE
Set up Repositories

### ISSUE THREAD

**Issue by ExtraGravity** [agriculture-capstone/class#42]
Setup a repository for, mobile app, webapp, server backend, and class.

**Comment by Parasrah** [comment]
Should we treat the agriculture-core as the backend repo for now? We can just replace the contents if we don't use the boilerplate

**Comment by Parasrah** [comment]
Does this include setting up the labels?

**Comment by ExtraGravity** [comment]
I actually don't know what completing this means. Closing for now.
