### ISSUE TITLE
Look into github private repos

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/class#44]

**Comment by mfalthaw** [comment]
Talked to Dr. Moshirpour, still didn't get back to us about this.

**Comment by Parasrah** [comment]
What are the implications of this for us? Does this effect our Zenhub account in any way?

**Comment by mfalthaw** [comment]
I don't know, how can we check that?

**Comment by mfalthaw** [comment]
@Right2Drive  We seem to be ok with Zenhub, we have a free license until Oct 04, 2018.

**Comment by jeinglis** [comment]
I just emailed the person at Github who emailed me in Sept asking if she could look into what is going on with this.

**Comment by jeinglis** [comment]
They can't talk to me about it since it is under Moshirpour's account. Moshirpour was CC'd on it so he should see it and hopefully will tackle it

**Comment by mfalthaw** [comment]
We've decided to keep going with public repos for now
