### ISSUE TITLE
Technical Specifications 

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/class#48]
All the specifications the final product must meet listed and described; i.e. size, dimensions, voltage limit, speed, etc.

15 marks

**Comment by jeinglis** [comment]
languages/frameworks/libraries
platform web & mobile
Testing platform
CI
Version Control
code hosting (github)
using any design patters ie MVC

**Comment by Parasrah** [comment]
@agriculture-capstone/developers If you guys could take a look at this at some point and make sure everything looks good that would be awesome! It's in its own document for the time being in the Task8 directory

**Comment by ExtraGravity** [comment]
Can we get a link in this issue?

**Comment by jeinglis** [comment]
I looked it over. There are a few sentences that felt awkwardly worded but overall think you did a great job of comparing our options.

 I think this might fit the Alternative solutions section better than technical specs. Based on the Tech specs section description, it sounds like they are looking for the tech specs our system must meet..... I'm not sure how we will do that, maybe network throughput and power usage, although I don't know how we would/ why we would put numbers to those. otherwise I don't know what kind of metrics we could give them that would fit in a table.

 I think we should  ask the TA what he wants for this section I don't know if it makes sense for software.
