### ISSUE TITLE
Docker Image for Core

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/class#59]
## Reviewer
Enoch
## QA
Brad

**Comment by jeinglis** [comment]
There is an issue running docker on my computers. I'm having trouble running docker. I checker the error and found this https://github.com/docker/for-win/issues/1098. Turns out docker wont run on windows home. I'll check which version I have on my desktop.... but Brad and Bea might run into the same issue

**Comment by ExtraGravity** [comment]
The native hyper-v version of docker won't run on windows home. But the legacy docker-toolbox will because it uses virtualbox virtualization as opposed to hyper-v virtualization. 

https://docs.docker.com/toolbox/overview/

**Comment by jeinglis** [comment]
We need to decide on ports to expose.

Also need to decide if the sql server will run in its own container or if it is going to run in this docker. I think it shoudl run in its own since the web app needs to hit the db as well

**Comment by ExtraGravity** [comment]
AFAIK the web app should only be interfacing with the API, the only thing that touches the database is the core, this limits how the database gets written to, kinda like making the database private and the-core is our public functions to it, @Right2Drive @beaesguerra thoughts?

In terms of where the sql server is, yes it's recommended to have one app per one container. docker-compose supports linking multiple containers together.

**Comment by Parasrah** [comment]
Wow we are super late looking at this, yeah I agree wholeheartedly, the only thing with access to the DB is the Core
