### ISSUE TITLE
EER Diagram

### ISSUE THREAD

**Issue by mfalthaw** [agriculture-capstone/class#63]

**Comment by mfalthaw** [comment]
hey @beaesguerra , please review

**Comment by beaesguerra** [comment]
I added a comment in the docs for it. Just a few minor fixes needed and then a question about the warehouse products. I'll copy and paste it here too:

The unique identifiers need to be underlined in the eer diagram.

> 
> There shouldn't be question marks in the farmer attributes. Freq is frequency and active is just active (this will help for when farmers are deleted)
> 
> the "has a" relationship should be a double diamond between the farmer and trader
> 
> Loans to price attribute should be amount instead of price
> 
> Other than that, it's great that you added the warehouse product parts but I'm not sure if we should add the warehouse product stuff? Since the requirements for this still aren't really solidified yet so I think they might be wrong? When we created this we weren't really sure yet and neither was JT. What are your thoughts on excluding the warehouse product related parts for the database? Then maybe we can just add a statement explaining why it's not part of it?

**Comment by mfalthaw** [comment]
Updated!
