### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by mfalthaw** [agriculture-capstone/class#64]

**Comment by mfalthaw** [comment]
hey @beaesguerra , please review this too

**Comment by beaesguerra** [comment]
Reviewed and added comments to the doc as well as here:

> 
> Unique and partial identifiers need to be underlined in the tables
> 
> TraderId for the farmer needs to have a dotted underline 
> 
> freq should be "PaymentFrequency" (this should also be payment frequency in the ER diagram too)
> 
> UserName for the User should be username (capitalizing Name implies that it's the user's name instead of a username)
> 
> This was our bad, but for the Supply Chain Manager table, can you add a column for "isAdmin" so that there's a way to differentiate between viewer supply chain managers and super admins?
> 
> loans_to should have partial keys for fid, tid, and id. and loans to should be amountvalue and amountunits instead of pricevalue and priceunits. I think transactionid that you have is equivalent to "id" but we need the ids of the trader and farmers as well per loan transaction
> 
> trades_with should also have partial keys for fid and tid (again we need to know for which trader and which farmer). 
> 
> And lastly, again, I'm not sure if we should include warehouse products because a lot of it is unknown (especially the relationship between traders and warehouse products)
>

**Comment by mfalthaw** [comment]
Updated!
